#
# frt
#
name: pre-release
on:
  workflow_dispatch:
#  push:
#    # Enable when testing release infrastructure on a branch.
#    # branches:
#    # - ag/work
#    tags:
#    - "[0-9]+.[0-9]+.[0-9]+"
env:
  # Set to force version number, e.g., when no tag exists.
  FRT_VERSION: v1.99.c
  TAG_NAME: pre-v1.99.c
  #CREATE_LS: true

jobs:
  build-windows:
    name: Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        include:
          - arch: x86
            platform: Win32
            pkg_suffix: x86

          - arch: x64
            platform: x64
            suffix: .x64
            pkg_suffix: x86_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Windows
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\"
        dir "C:\Program Files\Microsoft Visual Studio\2022"        
        cmd /c dir /b/s "C:\Program Files\Microsoft Visual Studio\"\cl.exe
        mkdir bin
        cl /Fo./bin/ frt.cpp frt_shared.c wildmat.c /link /out:bin/frt-${{ matrix.pkg_suffix }}.exe
        echo "ASSET=bin/frt-${{ matrix.pkg_suffix }}.exe" >> $GITHUB_ENV

    - name: Publish Release
      uses: deep-soft/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: |
          ${{ env.ASSET }}

  build-linux:
    name: build-linux
    runs-on: ${{ matrix.os }}
#    env:
#
    strategy:
      fail-fast: false
      matrix:
        build: [linux, linux-arm-aarch64, linux-arm-v7]
        include:
        - build: linux
          os: ubuntu-22.04
          arch: x86_64
          cc: [gcc]

        - build: linux-arm-aarch64
          os: ubuntu-22.04
          arch: aarch64
          cc: [gcc]
          
        - build: linux-arm-v7
          os: ubuntu-22.04
          arch: armv7
          cc: [gcc]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install packages (Ubuntu)
      continue-on-error: true
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sh ci/ubuntu-install-packages

    - name: Build release binary
      run: |
        mkdir bin
        if [ "$CC" == "" ]; then CC=gcc ; fi
        $CC frt.cpp frt_shared.c wildmat.c -o bin/frt-${{ matrix.arch }} "$@"
        echo "ASSET=bin/frt-${{ matrix.arch }}" >> $GITHUB_ENV

    - name: Strip release binary (linux)
      if: matrix.build == 'linux'
      run: strip ${{ env.ASSET }}

    - name: Strip release binary (linux-arm-aarch64)
      if: matrix.build == 'linux-arm-aarch64'
      run: strip ${{ env.ASSET }}

    - name: Strip release binary (linux-arm-v7)
      if: matrix.build == 'linux-arm-v7'
      run: strip ${{ env.ASSET }}

    - name: Publish Release
      uses: deep-soft/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: |
          ${{ env.ASSET }}
